#!/bin/bash

# Per-project configuration for the offline_leaf sync scripts (figleaf.sh / offleaf.sh).
#
# GENERATED BY leafsync.sh -- re-run leafsync.sh to recreate it.
#
# This file is committed into the Overleaf project and is deliberately
# MACHINE-INDEPENDENT: every value below is either derived at runtime or is a
# project-relative fragment. The same file is therefore correct on every
# machine, and no machine's copy can overwrite another's -- which is what used
# to happen when absolute paths were baked in here and the last push won.
#
# The single machine-specific value -- where the shared figure masters live --
# is read from leafsync's own per-machine config (FIGURES_BASE_DIR in
# ~/.config/leafsync/leafsync.conf), which is never committed.

# --- Derived: the clone is the directory this config file sits in -----------
# offleaf.sh and figleaf.sh source this file, so BASH_SOURCE[0] is this file.
GIT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)/"

# --- Derived: figure masters = this machine's figures base + project subpath -
# FIGURES_SUBPATH is project-relative and identical on every machine.
FIGURES_SUBPATH="__FIGURES_SUBPATH__"
_leafsync_conf="${XDG_CONFIG_HOME:-$HOME/.config}/leafsync/leafsync.conf"
[ -f "$_leafsync_conf" ] && . "$_leafsync_conf"
if [ -n "$FIGURES_BASE_DIR" ]; then
    WATCH_PATH_CONVERT="${FIGURES_BASE_DIR%/}/${FIGURES_SUBPATH}"
else
    WATCH_PATH_CONVERT=""
    printf '%s\n' "offleaf_config.sh: FIGURES_BASE_DIR is not set on this machine." >&2
    printf '%s\n' "Run leafsync.sh once so it can record where the shared figures live." >&2
    printf '%s\n' "(offleaf.sh does not need this; figleaf.sh does.)" >&2
fi
unset _leafsync_conf



#######################################
# Edits below this point should rarely if ever be needed
#######################################

# Path to directories where the optimized vector and bitmap files are kept
COPY_PATH_bitmap="${WATCH_PATH_CONVERT}../unwatched/prepress_bitmap/"
COPY_PATH_pdf="${WATCH_PATH_CONVERT}../unwatched/prepress_pdf/"

# Path to directories where the Overleaf repository keeps vector and bitmap files
COPY_PATH_bitmap_push="${GIT_PATH}figures/bitmap/"
COPY_PATH_vector_push="${GIT_PATH}figures/vector/"

# Path to temporary directory for optimized vector or converted bitmap files from figleaf.sh
TEMP_PATH="/tmp/"  # Temporary directory to store converted files

COMMIT_INTERVAL_SECONDS=3 # Minimum gap between commits
GIT_PULL_INTERVAL_SECONDS=90 # Interval to perform git pull in background (offleaf.sh); higher = fewer network wakeups
DEBOUNCE_SECONDS=5 # After an fswatch event is detected, wait this long before detecting another
POLL_INTERVAL_SECONDS=3 # How often the main loop wakes to check for changes when idle; higher = better battery

# Set to 1 for verbose diagnostic output from offleaf.sh/figleaf.sh, 0 to silence
DEBUG=0

# --- Derived: tool locations come from PATH, with a Homebrew fallback -------
FSWATCH="$(command -v fswatch || echo /opt/homebrew/bin/fswatch)"
CONVERT="$(command -v magick || echo /opt/homebrew/bin/magick)"

WATCH_PATH_OVERLEAF="$GIT_PATH"
OVERLEAF_ID="__OVERLEAF_ID__"

# Bold red for select outputs
RED="\033[1;31m"
RESET="\033[0m"
