#!/bin/bash

# Per-project configuration for the offline_leaf sync scripts (figleaf.sh / offleaf.sh).
#
# GENERATED BY leafsync.sh -- re-run leafsync.sh to recreate it.
#
# NOTE: GIT_PATH and WATCH_PATH_CONVERT below are ABSOLUTE, machine-specific
# paths. This file is committed into the Overleaf project for convenience, but
# those paths are only valid on the machine that generated it. A collaborator
# on a different machine must regenerate this file (run leafsync.sh) before
# running the sync scripts.

# Path to the Overleaf project repository (the local git clone). Must end in "/".
GIT_PATH="__GIT_PATH__"

# Path to the directory holding figure master versions, watched by figleaf.sh. Must end in "/".
WATCH_PATH_CONVERT="__WATCH_PATH_CONVERT__"



#######################################
# Edits below this point should rarely if ever be needed
#######################################

# Path to directories where the optimized vector and bitmap files are kept
COPY_PATH_bitmap="${WATCH_PATH_CONVERT}../unwatched/prepress_bitmap/"
COPY_PATH_pdf="${WATCH_PATH_CONVERT}../unwatched/prepress_pdf/"

# Path to directories where the Overleaf repository keeps vector and bitmap files
COPY_PATH_bitmap_push="${GIT_PATH}figures/bitmap/"
COPY_PATH_vector_push="${GIT_PATH}figures/vector/"

# Path to temporary directory for optimized vector or converted bitmap files from figleaf.sh
TEMP_PATH="/tmp/"  # Temporary directory to store converted files

COMMIT_INTERVAL_SECONDS=3 # Minimum gap between commits
GIT_PULL_INTERVAL_SECONDS=90 # Interval to perform git pull in background (offleaf.sh); higher = fewer network wakeups
DEBOUNCE_SECONDS=5 # After an fswatch event is detected, wait this long before detecting another
POLL_INTERVAL_SECONDS=3 # How often the main loop wakes to check for changes when idle; higher = better battery

# Set to 1 for verbose diagnostic output from offleaf.sh/figleaf.sh, 0 to silence
DEBUG=0

# Locations of fswatch and convert (filled in by leafsync.sh from your PATH)
FSWATCH="__FSWATCH__"
CONVERT="__CONVERT__"

WATCH_PATH_OVERLEAF="$GIT_PATH"
OVERLEAF_ID="__OVERLEAF_ID__"

# Bold red for select outputs
RED="\033[1;31m"
RESET="\033[0m"
